const global = {
  button1: {
    color: '#333',
    padding: '20px',
    width: '348px',
    background: '#ADFF00',
    borderRadius: '20px',
    fontWeight: 'bold',
  },
  button2: {
    background: '#E94057',
    color: '#333',
    padding: '20px',
    width: '348px',
    borderRadius: '20px',
    fontWeight: 'bold',
  },
  button2Small: {
    background: '#E94057',
    color: '#333',
    padding: '20px',
    borderRadius: '20px',
    height: ' 51px',
    width: ' 173px',
    fontWeight: 'bold',
  },
  button3: {
    color: '#333',
    padding: '20px',
    background: '#D4D4D4',
    borderRadius: '20px',
    fontWeight: 'bold',
    height: ' 51px',
    width: ' 173px',
  },
  button2xs: {
    margin: '0 5px',
    background: '#E94057',
    color: '#333',
    padding: '10px',
    borderRadius: '20px',
    width: '120px',
    height: '40px',
    fontWeight: 'bold',
  },
  button1xs: {
    margin: '0 5px',
    background: '#ADFF00',
    color: '#333',
    padding: '10px',
    borderRadius: '20px',
    width: '120px',
    height: '40px',
    fontWeight: 'bold',
  },
  textHeader: {
    color: '#E94057',
    fontWeight: 'bold',
  },
  badgeStatus: {
    margin: '0 5px',
    color: '#333',
    padding: '10px',
    borderRadius: '20px',
    width: '120px',
    height: '40px',
    fontWeight: 'bold',
  },
};
export default global;
